// This file is part of JrUtil and is licenced under the GNU AGPLv3 or later

namespace JrUtil.Tests

open System
open System.IO
open System.Text.Json
open Microsoft.VisualStudio.TestTools.UnitTesting

open JrUtil
open JrUtil.JdfPostScorer

[<TestClass>]
type JdfPostScorerTests() =
    let dataPath name = Path.Combine(__SOURCE_DIRECTORY__, "TestData", name)

    let optionalString (element: JsonElement) =
        if element.ValueKind = JsonValueKind.Null then None else Some(element.GetString())

    /// Generated by `uv run python -m post_scorer.golden` (jrutil/scripts/post-scorer)
    /// from the Ústecký candidate table and the production model.
    [<TestMethod>]
    member _.``Learned scorer matches the Python reference on the golden stops``() =
        use document = JsonDocument.Parse(File.ReadAllText(dataPath "post-scorer-golden.json"))
        let root = document.RootElement
        let model = parseModel (root.GetProperty("model"))
        let mutable compared = 0
        for stop in root.GetProperty("stops").EnumerateArray() do
            let contexts =
                stop.GetProperty("contexts").EnumerateArray()
                |> Seq.map (fun c ->
                    { contextId = c.GetProperty("context_id").GetString()
                      previousStop = optionalString (c.GetProperty("previous_stop"))
                      nextStop = optionalString (c.GetProperty("next_stop"))
                      stopPostCount = c.GetProperty("stop_post_count").GetInt32() })
                |> Seq.toArray
            let rows = stop.GetProperty("candidates").EnumerateArray() |> Seq.toArray
            let candidates =
                rows |> Array.map (fun c ->
                    { Candidate.contextId = c.GetProperty("context_id").GetString()
                      hypothesisId = c.GetProperty("hypothesis_id").GetString()
                      postId = c.GetProperty("post_id").GetString()
                      areaId = c.GetProperty("area_id").GetString()
                      isPlatform = c.GetProperty("is_platform").GetBoolean()
                      features = c.GetProperty("features").EnumerateArray() |> Seq.map _.GetDouble() |> Seq.toArray })
            let ordered, stage1, stage2 = stopProbabilities model contexts candidates
            let expected =
                rows |> Array.map (fun c ->
                    (c.GetProperty("context_id").GetString(), c.GetProperty("hypothesis_id").GetString()),
                    (c.GetProperty("stage1_probability").GetDouble(), c.GetProperty("stage2_probability").GetDouble()))
                |> dict
            ordered |> Array.iteri (fun index c ->
                let first, second = expected.[(c.contextId, c.hypothesisId)]
                Assert.AreEqual(first, stage1.[index], 1e-9, $"stage 1 {c.contextId} {c.hypothesisId}")
                Assert.AreEqual(second, stage2.[index], 1e-9, $"stage 2 {c.contextId} {c.hypothesisId}"))
            let decisions = scoreStop model contexts candidates |> Array.map (fun d -> d.contextId, d) |> dict
            for d in stop.GetProperty("decisions").EnumerateArray() do
                let contextId = d.GetProperty("context_id").GetString()
                let actual = decisions.[contextId]
                Assert.AreEqual(d.GetProperty("resolution").GetString(), string actual.resolution, contextId)
                Assert.AreEqual(optionalString (d.GetProperty("hypothesis_id")), actual.hypothesisId, contextId)
                Assert.AreEqual(d.GetProperty("post_probability").GetDouble(), actual.postProbability, 1e-9, contextId)
                Assert.AreEqual(d.GetProperty("area_probability").GetDouble(), actual.areaProbability, 1e-9, contextId)
                compared <- compared + 1
        Assert.IsTrue(compared > 100, $"golden fixture too small: {compared} decisions")

    [<TestMethod>]
    member _.``Posts never contain one source twice or two local refs``() =
        // Four points within 10 m: a and b share source S, c carries local_ref 2.
        let latitudes = [| 50.0; 50.00005; 50.00002; 50.00003 |]
        let longitudes = [| 14.0; 14.0; 14.00005; 14.00002 |]
        let sources = [| [| "S" |]; [| "S" |]; [| "T" |]; [| "U" |] |]
        let refs = [| Some "1"; None; Some "2"; None |]
        let posts = clusterPosts latitudes longitudes sources refs
        Assert.AreNotEqual(posts.[0], posts.[1])
        Assert.AreNotEqual(posts.[0], posts.[2])
        Assert.AreEqual(4, posts.Length)

    [<TestMethod>]
    member _.``Posts farther apart than 25 m stay separate``() =
        let posts = clusterPosts [| 50.0; 50.0003 |] [| 14.0; 14.0 |] [| [| "S" |]; [| "T" |] |] [| None; None |]
        Assert.AreNotEqual(posts.[0], posts.[1])
        let near = clusterPosts [| 50.0; 50.0001 |] [| 14.0; 14.0 |] [| [| "S" |]; [| "T" |] |] [| None; None |]
        Assert.AreEqual(near.[0], near.[1])

    [<TestMethod>]
    member _.``Areas never mix tram and road posts``() =
        let areas = clusterAreas [| 50.0; 50.0001; 50.0002 |] [| 14.0; 14.0; 14.0 |] [| "road"; "tram"; "road" |]
        Assert.AreNotEqual(areas.[0], areas.[1])
        Assert.AreEqual(areas.[0], areas.[2])
        let any = clusterAreas [| 50.0; 50.0001 |] [| 14.0; 14.0 |] [| "road"; "any" |]
        Assert.AreEqual(any.[0], any.[1])

    [<TestMethod>]
    member _.``Model parsing rejects a stage 2 without the collective features``() =
        let stage features =
            let values = features |> Array.map (fun _ -> "0.0") |> String.concat ","
            let scales = features |> Array.map (fun _ -> "1.0") |> String.concat ","
            let names = features |> Array.map (sprintf "\"%s\"") |> String.concat ","
            $"""{{"format":"{StageFormat}","features":[{names}],"mean":[{values}],"scale":[{scales}],"weights":[{values}],"null_utility":0.0,"threshold":0.5}}"""
        let document (second: string array) =
            $"""{{"format":"{ModelFormat}","stage1":{stage [| "side" |]},"stage2":{stage second},"thresholds":{{"simple":0.8,"complex":0.9,"area":0.7}}}}"""
        use valid = JsonDocument.Parse(document (Array.append [| "side" |] CollectiveColumns))
        let model = parseModel valid.RootElement
        Assert.AreEqual(Some 0.7, model.thresholds.area)
        use invalid = JsonDocument.Parse(document [| "side" |])
        Assert.Throws<ArgumentException>(fun () -> parseModel invalid.RootElement |> ignore) |> ignore

    [<TestMethod>]
    member _.``Uncertain contexts fall back to the area, then abstain``() =
        let stage features weights =
            { features = features; mean = Array.zeroCreate features.Length
              scale = Array.create features.Length 1.0; weights = weights; nullUtility = -10.0 }
        let model thresholds =
            { stage1 = stage [| "x" |] [| 0.0 |]
              stage2 = stage (Array.append [| "x" |] CollectiveColumns) (Array.zeroCreate 7)
              thresholds = thresholds }
        // Two equally likely posts (0.5 each) in one area.
        let contexts = [| { contextId = "c"; previousStop = Some "p"; nextStop = Some "n"; stopPostCount = 2 } |]
        let candidate hypothesis post =
            { Candidate.contextId = "c"; hypothesisId = hypothesis; postId = post; areaId = "A"
              isPlatform = false; features = [| 0.0 |] }
        let candidates = [| candidate "h1" "P1"; candidate "h2" "P2" |]
        let decide thresholds = (scoreStop (model thresholds) contexts candidates).[0]
        let area = decide { simple = 0.9; complexStop = 0.9; area = Some 0.8 }
        Assert.AreEqual(Area, area.resolution)
        Assert.AreEqual(Some "h1", area.hypothesisId)
        Assert.AreEqual(Abstain, (decide { simple = 0.9; complexStop = 0.9; area = None }).resolution)
        Assert.AreEqual(Physical, (decide { simple = 0.4; complexStop = 0.9; area = None }).resolution)
